---

exclude: '(vault|dist|plugins)'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: end-of-file-fixer

- repo: https://github.com/adrienverge/yamllint
  rev: v1.18.0
  hooks:
  - id: yamllint
    entry: yamllint
    language: python
    types: [file, yaml]

- repo: https://github.com/haani-niyaz/hadolint-pre-commit
  rev: no-script
  hooks:
  - id: hadolint
    name: Hadolint runner
    description: Run Hadolint to link Dockerfile
    entry: hadolint_docker_run.py

# - repo: https://github.com/golangci/golangci-lint
#   rev: v1.21.0
#   hooks:
#   - id: golangci-lint
#     name: golangci-lint
#     description: Fast linters runner for Go.
#     entry: golangci-lint run --fix
#     types: [go]
#     language: golang
#     pass_filenames: false
