openapi: "3.0.0"

info:
  version: 1.0.0
  title: PatientSky One Time User API
  description: API to generate temporary one time users from LDAP backend
  contact:
    name: PatientSky Infrastructure Team
    email: kj@patientsky.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
    
servers:
  - url: https://odn1-inf-otu.privatedns.zone/api/v1
  - url: https://osl1-inf-otu.privatedns.zone/api/v1
  - url: https://cph1-inf-otu.privatedns.zone/api/v1
  - url: https://sto1-inf-otu.privatedns.zone/api/v1
  
paths:

  # -------------------
  # Ping
  # -------------------
  
  /ping:
    get:
      tags:
        - Ping
      summary: Check server is alive
      description: Check if server is answering
      operationId: ping
      responses:
        '200':
          description: Successful result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ping'

  # -------------------
  # Auth
  # -------------------
  
  /auth/verify:
    get:
      security:
        - BearerAuth: []
      tags:
        - Auth
      summary: Verify token
      description: Verify JWT token is valid
      operationId: authVerify
      responses:
        '200':
          description: Successful result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Verify'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
          
  /auth/authorize:
    post:
      tags:
        - Auth
      summary: Authenticate
      description: Authenticate with LDAP credentials
      operationId: authAuthenticate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Authorize'
      responses:
        '200':
          description: Successful result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authorize'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  # -------------------
  # User  
  # -------------------
  
  /users:
    get:
      tags:
        - Users
      security:
        - BearerAuth: []
      summary: Get active users
      description: Get active users created by self
      operationId: getUsers
      responses:
        '200':
          description: Successful result
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'          
    
  # -------------------
  # LDAP-Group
  # -------------------
  /ldap-groups:
  
    get:
      tags:
        - LDAP-Groups
      security:
        - BearerAuth: []
      summary: Get all LDAP groups
      description: Returns list of the LDAP groups the user is a member of
      operationId: getAllLDAPGroups
      responses:
        '200':
          description: Successful result
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LDAPGroup'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  # -------------------
  # OTU-Group
  # -------------------
        
  /ldap-groups/{ldap_group_name}/otu-groups:
    
    post:
      tags:
        - LDAP-Groups
      security:
        - BearerAuth: []
      summary: "Create one time user group"
      description: "Users in this LDAP group can create an one time user group. This group is mapped from glauth"
      operationId: "createGroup"
      parameters:
        - name: ldap_group_name
          in: path
          description: LDAP group name
          required: true
          x-example: "proxy-sql"
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OTUGroupNew'
      responses:
        '200':
          description: User response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OTUGroup'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '409':
          $ref: '#/components/responses/ConflictError'
      
    get:
      tags:
        - LDAP-Groups
      security:
        - BearerAuth: []
      summary: "Get otu-groups for one time user generation"
      description: "Returns otu-groups created for this LDAP group. Users can create one time users from these groups."
      operationId: "getGroups"
      parameters:
        - name: ldap_group_name
          in: path
          description: LDAP group name
          required: true
          x-example: "proxy-sql"
          schema:
            type: string
      responses:
        '200':
          description: Successful result
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OTUGroup'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'        
          
  /otu-groups/{group_name}:
  
    delete:
      tags:
        - OTU-Groups
      security:
        - BearerAuth: []
      summary: "Delete otu-group"
      description: "Deletes otu-group and invalidates all users"
      operationId: "deleteOTUGroup"
      parameters:
        - name: group_name
          in: path
          description: LDAP group name
          required: true
          x-example: "proxy-sql"
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '404':
          $ref: '#/components/responses/NotFoundError'

  /otu-groups/{group_name}/users:
  
    post:
      tags:
        - OTU-Groups
      security:
        - BearerAuth: []
      summary: "Generate a new one time user"
      description: "Generate a one time user for the specific otu-group"
      operationId: "generateOTUUser"
      parameters:
        - name: group_name
          in: path
          description: LDAP group name
          required: true
          x-example: "proxy-sql"
          schema:
            type: string
      responses:
        '201':
          description: User response
          content:
            application/json:
              schema:                
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
          
    get:
      tags:
        - OTU-Groups
      security:
        - ApiKeyAuth: []
      summary: "Get all users in otu-group"
      description: "Get all users in a given otu-group."
      operationId: "getOTUGroupUsers"
      parameters:
        - name: group_name
          in: path
          description: LDAP group name
          required: true
          x-example: "proxy-sql"
          schema:
            type: string
      responses:
        '200':
          description: Successful result
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'            
                  
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedErrorAPIKey'        
  

security:

  - ApiKeyAuth: []
  - BearerAuth: []

components:

  responses:
        
    ForbiddenError:
      $ref: "#/components/schemas/ForbiddenError"
    ValidationError:
      $ref: "#/components/schemas/ValidationError"
    UnauthorizedError:
      description: Access token is missing or invalid
    ConflictError:
      description: Item already exists
    UnauthorizedErrorAPIKey:
      description: API key s missing or invalid
    NotFoundError:
      description: Not found

  securitySchemes:
  
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY

  schemas:

    # -------------------
    # Error
    # -------------------
    
    ForbiddenError:
      description: Not allowed access to this resource
      type: "object"
      properties:
        forbidden_error:
          type: "object"
            
    ValidationError:
      description: Bad request
      type: "object"
      properties:
        validation_error:
          type: "object"

    # -------------------
    # Ping  
    # -------------------

    Ping:
      type: "object"
      properties:
        version:
          type: "string"
          example: "v1.0.1"
        message:
          type: "string"
          example: "pong"
  
    # -------------------
    # Auth  
    # -------------------

    Verify:
      type: "object"
      properties:
        token:
          type: "string"
          example: "yRQYnWzskCZUxPwaQupWkiUzKELZ49eM7oWxAQK_ZXw"
          
    Authorize:
      type: "object"
      properties:
        username:
          type: "string"
          example: "kj"
          description: LDAP username
        password:
          description: LDAP password + OTP token
          type: "string"
          example: "password+otp"

    # -------------------
    # LDAP-Group
    # -------------------

    LDAPGroup:
      type: "object"
      properties:
        ldap_group_name:
          type: string
          example: proxy-sql

    # -------------------
    # OTUGroup
    # -------------------
    
    OTUGroupCustomProps:
      type: "object"
      properties:
        key_name_1:
          type: string
          example: "key_name_1_value"
        key_name_2:
          type: string
          example: "key_name_2_value"
        key_name_3:
          type: integer
          example: 3
    
    OTUGroup:
      type: "object"
      properties:
        group_name:
          type: string
          example: proxy-sql
        ldap_group_name:
          type: string
          example: proxy-sql
        lease_time:
          type: integer
          example: 720 # 12 hours
          description: Lease time in minutes
        custom_properties:
          $ref: '#/components/schemas/OTUGroupCustomProps'
        create_time:
          type: integer
          example: 1554102608          
        create_by:
          type: string
          example: kj
          
    OTUGroupNew:
      type: "object"
      properties:
        group_name:
          type: string
          example: proxy-sql
        ldap_group_name:
          type: string
          example: proxy-sql
        lease_time:
          type: integer
          example: 720 # 12 hours 
          description: Lease time in minutes
  
    # -------------------
    # User  
    # -------------------

    User:
      required:
        - name  
      properties:
        username:
          type: "string"
          example: "kj-proxy-sql-yx4dajg8vn"
        password:
          type: "string"
          example: "jkybs9p8uukysmfarapf"
        group_name:
          type: "string"
          example: "proxy-sql"
        expire_time:
          type: "integer"
          example: 1554102608
        create_time:
          type: "integer"
          example: 1554100608
        create_by:
          type: "string"
          example: "kj"