---

name: Integration
on:
  pull_request:
    branches:
    - master
    - development

jobs:

  linters:

    name: Linters
    runs-on: ubuntu-18.04

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
      - name: dockerfile-linter
        id: dockerfile-linter
        uses: pasientskyhosting/github-actions/dockerfile-linter@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: golangci-lint
        id: golangci-lint
        uses: pasientskyhosting/github-actions/golangci-lint@v0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
