---

name: Integration
on:
  pull_request:
    branches:
    - master
    - development

jobs:

  dockerfile_lint:

    name: dockerfile_lint_job
    runs-on: ubuntu-18.04

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
      - name: dockerfile-linter
        id: dockerfile-linter
        uses: pasientskyhosting/github-actions/dockerfile-linter@v0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  golangci_lint:
    name: golangci_lint_job
    runs-on: ubuntu-latest
    container:
      image: golang:1.12.4
      env:
        GOPATH: /__w/ps-otu-ldap/go/
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/src/github.com/pasientskyhosting/ps-otu-ldap

    - name: Setup
      run: |
        cd ./server/src
        go get -d

    - name: golangci-lint
      id: golangci-lint
      uses: pasientskyhosting/github-actions/golangci-lint@v0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        golangci_lint_flags: "--enable-all"
        level: warning

    # - name: Debug
    #   run: |
    #     pwd
    #     echo ${HOME}
    #     echo ${GITHUB_WORKSPACE}
    #     echo ${GOPATH}
    #     echo ${GOROOT}

  # golangci_lint:

  #   name: golangci_lint_job
  #   runs-on: ubuntu-18.04

  #   steps:

  #     - name: Check out code into the Go module directory
  #       uses: actions/checkout@master
  #       with:
  #         fetch-depth: 1
  #         path: go/src/github.com/pasientskyhosting/ps-otu-ldap
      
  #     - name: Setup go
  #       uses: actions/setup-go@v1
  #       with:
  #         go-version: '1.13'

  #     - name: Debug
  #       run: |
  #         pwd
  #         echo ${HOME}
  #         echo ${GITHUB_WORKSPACE}
  #         echo ${GOPATH}
  #         echo ${GOROOT}
  #       env:
  #         GOPATH: /home/runner/work/pasientskyhosting/go

  #     - name: Setup dependecies
  #       run: go get -d
  #       env:
  #         GOPATH: /home/runner/work/pasientskyhosting/go

  #     - name: golangci-lint
  #       uses: docker://reviewdog/action-golangci-lint:v1.0.4 # pre-build docker image
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         golangci_lint_flags: "--enable-all"
  #         level: warning
  #         tool_name: errcheck
  #       env:
  #         GOPATH: /home/runner/work/pasientskyhosting/go
  #     # - name: golangci-lint
  #     #   id: golangci-lint
  #     #   uses: pasientskyhosting/github-actions/golangci-lint@v0.3
  #     #   with:
  #     #     github_token: ${{ secrets.GITHUB_TOKEN }}
  #     #     golangci_lint_flags: "--enable-all"
  #     #     level: warning
