---

name: Integration
on:
  push:
    branches:
    - development
  pull_request:
    branches:
    - master
    - development

jobs:

  docker_build:

    name: docker_build_job
    runs-on: ubuntu-latest

    steps:

      - name: Docker build
        uses: docker://pasientskyhosting/action-docker-build-push:latest
        with:
          image_name: pasientskyhosting/ps-otu-ldap
          build_only: 'true'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  dockerfile_lint:

    name: dockerfile_lint_job
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: dockerfile-linter
        id: dockerfile-linter
        uses: docker://pasientskyhosting/action-dockerfile-linter:latest
        with:
          dockerfile: ./Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  golangci_lint:

    name: golangci_lint_job
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: golangci-lint
        id: golangci-lint
        uses: docker://pasientskyhosting/action-golangci-lint:latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          go_get: './server/src'

  golang_test:

    name: golang_test_job
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v1      

      - name: Setup go for tests
        uses: actions/setup-go@v1.1.1
        with:
          go-version: '1.12.5' # The Go version to download (if necessary) and 
          
      - name: Run tests
        id: go_run_test
        env:
          API_ENCRYPTION_KEY: 'thisisverysecurepassword'
          API_DB_FILE: '/home/runner/work/ps-otu-ldap/ps-otu-ldap/db/otu.db'
          API_LDAP_BIND_DN: 'uid=bind,cn=sysaccounts,cn=accounts,dc=pasientsky,dc=no'
          API_LDAP_SERVER: 'somer-ldap-server.example.com'
          API_LDAP_BIND_PASSWORD: 'somePassword12345!'
          API_JWT_SECRET: 'tokenssecret'
          API_KEY: 'apikeysecret'
          API_LISTEN: '0.0.0.0:8081'
        run: |          
          cd server/src
          go get -d
          go test

