---

name: Integration
on:
  pull_request:
    branches:
      - master

jobs:

  docker_build_job:

    name: docker_build_job
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: Docker build
        uses: docker://pasientskyhosting/action-docker-build-push:latest
        with:
          image_name: pasientskyhosting/ps-otu-ldap
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  pre_commit_job:

    name: pre_commit_job
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - uses: docker://pasientskyhosting/action-pre-commit:python-v3.7.7
        id: pre_commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  golang_api_test_job:

    name: golang_api_test_job
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup go for tests
        uses: actions/setup-go@v2
        with:
          go-version: '1.12.5'

      - name: Run tests
        id: go_run_test
        env:
          API_ENCRYPTION_KEY: 'thisisverysecurepassword'
          API_DB_FILE: '/home/runner/work/ps-otu-ldap/ps-otu-ldap/db/otu.db'
          API_LDAP_BIND_DN: 'uid=bind,cn=sysaccounts,cn=accounts,dc=pasientsky,dc=no'
          API_LDAP_SERVER: 'somer-ldap-server.example.com'
          API_LDAP_BIND_PASSWORD: 'somePassword12345!'
          API_JWT_SECRET: 'tokenssecret'
          API_KEY: 'apikeysecret'
          API_LISTEN: '0.0.0.0:8081'
          GO111MODULE: on
        run: |
          cd server/src
          go get
          go test
