---

name: A workflow for validating the One Time User project
on:
  pull_request:
    branches:
    - master
    - development

jobs:

  build:
    name: sjkaliski/go-github-actions/fmt@v0.5.0
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: gofmt
      uses: sjkaliski/go-github-actions/fmt@v0.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
    - name: golint
      uses: sjkaliski/go-github-actions/lint@v0.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
