---

# Runs your workflow anytime the release event occurs  
name: Release
on:
  release:
    types: [published]

jobs:

  docker_build_push:

    name: docker_build_push
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: Docker publish
        uses: pasientskyhosting/github-actions/docker-publish@master
        with:
          image_name: pasientskyhosting/ps-otu-ldap
          build_only: 'false'
          dockerfile_path: ./Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
