---

# Runs your workflow anytime the release event occurs  
name: Release Management
on:
  release:
    types: [published]
  push:
    branches:
      - master
      - development

jobs:

  update_draft_release_job:
    runs-on: ubuntu-latest
    steps:
      - uses: toolmantim/release-drafter@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker_build_push:

    name: docker_build_push
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: Docker publish
        uses: docker://pasientskyhosting/action-docker-build-push:latest
        with:
          image_name: pasientskyhosting/ps-otu-ldap
          build_only: 'false'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
