---

# Runs your workflow anytime the release event occurs  
name: Release
on:
  release:
    types: [published]

jobs:

  docker_publish:

    name: docker_publish_job
    runs-on: ubuntu-18.04

    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: docker-publish
        id: docker-publish
        uses: pasientskyhosting/github-actions/docker-publish@master
        with:
          repo_name: pasientskyhosting/ps-otu-ldap
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
